master-data:
  bank-accounts:
  - 2141313009163
  bank-filters:
  - None
  - BdREN
  - Software
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jan23.
  - Feb23.
  - Mar23.
  - Apr23.
  - May23.
  - Jun23.
  - Jul23.
  - Aug23.
  - Sep23.
  - Oct23.
  - Nov23.
  - Dec23.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '2141313009163'
  selected-filter: None
  selected-mode: Bank
  selected-month: Apr23.
  selected-reference: 23/1144
  selected-wing: Acquisition
