master-data:
  bank-accounts:
  - 2141313009163
  bank-filters:
  - None
  - Software
  - R&D
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jan24.
  - Feb24.
  - Mar24.
  - EidBouns-Apr24.
  - Apr24.
  - May24.
  - EidBouns-Jun24.
  - Jun24.
  - Jul24.
  - Aug24.
  - Sep24.
  - Oct24.
  - Nov24.
  - Dec24.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '2141313009163'
  selected-filter: None
  selected-mode: Cheque
  selected-month: Mar24.
  selected-reference: 24/1300
  selected-wing: Delivery
