master-data:
  bank-accounts:
  - 2141313009163
  bank-filters:
  - None
  - Software
  - R&D
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jul24.
  - Aug24.
  - Sep24.
  - Oct24.
  - Nov24.
  - Dec24.
  - Jan25.
  - Feb25.
  - Mar25.
  - Apr25.
  - May25.
  - Jun25.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '2141313009163'
  selected-filter: None
  selected-mode: Bank
  selected-month: Jun24.
  selected-reference: 24/1300
  selected-wing: Delivery
