master-data:
  bank-accounts:
  - 14131050002359
  - 14111060000068
  bank-filters:
  - None
  - BdREN
  - Software
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Feb22.
  - Mar22.
  - Apr23.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '14111060000068'
  selected-filter: Software
  selected-mode: Bank
  selected-month: Feb22.
  selected-reference: 22/891
  selected-wing: Operations
