master-data:
  bank-accounts:
  - 2141313009163
  bank-filters:
  - None
  - Software
  - R&D
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jan26.
  - Feb26.
  - Mar26.
  - Apr26.
  - May26.
  - Jun26.
  - Jul26.
  - Aug26.
  - Sep26.
  - Oct26.
  - Nov26.
  - Dec26.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '2141313009163'
  selected-filter: None
  selected-mode: Bank
  selected-month: Jan26.
  selected-reference: 26/001
  selected-wing: Delivery
