master-data:
  bank-accounts:
  - 2141313009163
  bank-filters:
  - None
  - BdREN
  - Software
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jul22.
  - Aug22.
  - Sep22.
  - Oct22.
  - Nov22.
  - Dec22.
  - Jan23.
  - Feb23.
  - Mar23.
  - Apr23.
  - May23.
  - Jun23.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '2141313009163'
  selected-filter: Software
  selected-mode: Cash
  selected-month: Jul22.
  selected-reference: 22/973
  selected-wing: Acquisition
